### ISSUE TITLE
“Yes, but you see, I do not enjoy pain”

### ISSUE THREAD

**Issue by JupiterSayuri451** [Swipefly/bookishere#50]

**Comment by Swipefly** [comment]
This quote has been translated many different ways over the years, but the general consensus is that The Salty One is trying to explain that although he endures the pain of a thousand suns for his disciples, he has not gotten familiar to the pain nor pushed it from his mind. Pain strengthens us, brings us together, and protects us from danger. Without pain, we could not serve Salt to the best of our abilities. That said, pain holds us back. Sometimes pain is unnecessary, and sometimes it is critical. We must consider the nature of our pain before we take drugs or use healing salves, and decide for ourselves whether The Salty One would do the same. We must walk in His footsteps, for He is a shining example of one who has become one with Salt.
